### ISSUE TITLE
This project is very cool, will you discuss the architecture of the application?

### ISSUE THREAD

**Issue by kitgary** [jagenjo/webglstudio.js#14]
Hi, just check out this project, amazing! I am learning WebGL, will you consider to write a blog post about the technical details and architecture of this application?

Thanks!

**Comment by coderofsalvation** [comment]
The stack is  briefly explained here: https://webglstudio.org/doc/

each component has its own repo with its own documentation.
Hope this helps.

ps. I think we can close this issue
