### ISSUE TITLE
Suggestion: Javascript database instead mysql

### ISSUE THREAD

**Issue by magadan** [jagenjo/webglstudio.js#18]
Another suggestion: instead use mysql database, why not use a sql serverless JavaScript Database ?

https://github.com/kripken/sql.js/

http://www.forerunnerdb.com/

http://www.taffydb.com/

https://pouchdb.com/

http://lokijs.org/#/

**Comment by jagenjo** [comment]
Because that would mean you need to run SQL in the server, and the idea is that the server is very lightweight so it can run with any Apache + PHP + MySQL
