### ISSUE TITLE
OpenCTM support !

### ISSUE THREAD

**Issue by magadan** [jagenjo/webglstudio.js#21]
Pls, add a OpenCTM support, its a very compact format

http://openctm.sourceforge.net/

**Comment by coderofsalvation** [comment]
hm I noticed this: https://github.com/jagenjo/webglstudio.js/blob/master/plugins/scripts/ctmparser.js

Does it means this issue can be closed (for now)?

**Comment by jagenjo** [comment]
yes, although it is using a plugin
