### ISSUE TITLE
installation process or cheatsheet for ubuntu

### ISSUE THREAD

**Issue by johnfelipe** [jagenjo/webglstudio.js#23]
stay alert

**Comment by jagenjo** [comment]
good

**Comment by johnfelipe** [comment]
@jagenjo i need document with installation process bro

**Comment by jagenjo** [comment]
I have created this guide: 

https://github.com/jagenjo/webglstudio.js/blob/master/INSTALL.md

**Comment by johnfelipe** [comment]
i can install with php7 and nginx?

**Comment by jagenjo** [comment]
yes, that how I have it now

**Comment by johnfelipe** [comment]
can we have a hangout for correct installation?
Pls accept my invitation sent u before to javi.agenjo@gmail.com
