### ISSUE TITLE
Can publish architecture models?

### ISSUE THREAD

**Issue by johnfelipe** [jagenjo/webglstudio.js#28]
Can I publish models of buildings for my clients for not create videos

**Comment by jagenjo** [comment]
Importing meshes from 3D architecture programs is not very well supported, you should check clev3r.io o sketchfab

**Comment by johnfelipe** [comment]
but i need something locally and web based, clev3r.io is offline, and sketchfab is a third party application, is possible something like your application web bassed for my clients view in chrome or firefox without need render and create a video?

**Comment by jagenjo** [comment]
It could be used, but right now importing 3D scenes from 3D programs is not perfectly supported and lots of features are missing. You can try but I cannot recommend it because it wont be straight to do it.
