### ISSUE TITLE
how to use three.js component?

### ISSUE THREAD

**Issue by tornadory** [jagenjo/webglstudio.js#29]
Hi all,

I found that there is one component named threejs , sounds like it can support three.js as well.

But when I tried to add threejs component, seems there are some errors and not successful.

Can anyone tell me can I use it or how to use it?

**Comment by jagenjo** [comment]
Hi:

I did the Three.JS component long time ago so I hadnt check it with the latest updates.
I will try to fix it this week and add a tutorial of how to use it soon.

Cheers

**Comment by tornadory** [comment]
@jagenjo  wow, great, thanks very much!

**Comment by johnnyz2017** [comment]
it seems that use old version of three.js can make it work, such as r73.

the newest version can not.

**Comment by jagenjo** [comment]
yes, I was trying to fix the error but the new Three.JS has deprecated the function that reset its render engine, and without it it is hard to integrate both render engines because they change states.

**Comment by johnnyz2017** [comment]
@jagenjo  hope you can fix it soon.  and I have a question in here that the 3D objects created via script (both litegl.js and three.js) can be access via the scene graph? or can they interact with each other?

many thanks for your help to understand it better.

**Comment by jagenjo** [comment]
No, because the editor doesnt know about them. But if you create the 3d objects using the LiteScene API then yes.

**Comment by tornadory** [comment]
@jagenjo  thanks for your update, hope you can fix it ASAP.

**Comment by jagenjo** [comment]
ok, I fixed it, here is an example of scene:

http://www.tamats.com/projects/webglstudio/editor/fileserver/files//guest/projects/features/threeJS.scene.json

**Comment by tornadory** [comment]
@jagenjo  cool!  but I can not see anything from this scene, just a black screen, need the player do something else? I just use the load-scene example to load it.

**Comment by jagenjo** [comment]
Did you opened from the editor? you need to press play to see it.

**Comment by tornadory** [comment]
@jagenjo  I upload it into webglstudio but can not open it as a scene, editor warning that "Insert not implemented for this resource type: Resource"

@jagenjo  before that, I tried to use litescene (Player) directly to open it(have updated all of the current script)

**Comment by jagenjo** [comment]
go to webglstudio -> project -> load -> from URL
and paste the URL I gave you

**Comment by tornadory** [comment]
@jagenjo  sorry, too late to reply, but still not work, some error shows when I tried to run it:


three.min.js:539 Uncaught TypeError: Cannot assign to read only property 'getAttribute' of object '#<F>'

Uncaught TypeError: THREE.Scene is not a constructor


seems that ThreeJS still not loaded normally.

**Comment by jagenjo** [comment]
Strange, I fixed that bug in LiteScene. Are you sure you are using the latest version from the repository?

**Comment by tornadory** [comment]
I just used http://webglstudio.org/demo/, so you mean I need use litescene directly? oh...

**Comment by jagenjo** [comment]
Sorry, that version usually has the old version because is the stable one, if you want the new features always go to  http://webglstudio.org/latest/

**Comment by tornadory** [comment]
@jagenjo  cool, I got it.

I downloaded the scene file and use load from file function and finally it works, I see the cube.

It's great!
