### ISSUE TITLE
license? copyright?

### ISSUE THREAD

**Issue by scottdraves** [jagenjo/webglstudio.js#3]
please add banners to all source files and  a LICENSE file.

**Comment by jagenjo** [comment]
To all files? Wow, didnt know that. I will

**Comment by scottdraves** [comment]
if you haven't decided already, i recommend the apache 2 license because of its patent protections.

great work btw, many thanks for developing and releasing!

**Comment by Calinou** [comment]
> To all files? Wow, didnt know that. I will

It is preferred to add a licensing header to all files in order to avoid confusion; most popular licenses provide pre-made headers for that, where you just have to add your own copyright line.

You do not have to do this, but I would personally recommend doing it anyway.

**Comment by silverkorn** [comment]
It's MIT Licensed guys...
Look at the end of his main website: http://webglstudio.org/

BTW @jagenjo, thanks for this wonderful licensing, extremely appreciated! :smile:

**Comment by Calinou** [comment]
> It's MIT Licensed guys...

How is "MIT License" on a page legally binding in any way? :suspect:

**Comment by jagenjo** [comment]
Sorry litescene and litegl all have licenses in their repos but i forgot to add it to this repo

**Comment by liam-middlebrook** [comment]
@Calinou I'm not a Lawyer but code is code. He can license it however he wants, but @jagenjo from what I've seen most commonly. It's a good idea for you to put some kind of LICENSE or COPYING file at the base of this repository that at least covers anything that isn't explicitly licensed in source files.

**Comment by jagenjo** [comment]
I have added the LICENSE file with the MIT License to the code, but I have to say that for the other libraries I didnt add the same one, I probably will change it to MIT too.

**Comment by silverkorn** [comment]
Actually your __lite__ series looks pretty all MIT Licensed about what I've read in their LICENCE file but just without the clear indication within them.

**Comment by mcanthony** [comment]
Thank you btw for this wonderful contribution. This is by far the best WebGL environment I have seen to date, and I look forward to contributing to what I think will be the premier open source editor for WebGL.

**Comment by TheKnarf** [comment]
This issue can probably be closed now?

**Comment by jagenjo** [comment]
yup
