### ISSUE TITLE
Problem in loading .obj file

### ISSUE THREAD

**Issue by sushmitacse** [jagenjo/webglstudio.js#31]
After saving a scene with .obj files in local , when trying to load the scene ,  .obj files resources not getting loaded for which I am just getting a point on the screen not the entire mesh, texture nothing. May I know why ? Please help me asap..

**Comment by jagenjo** [comment]
saving locally only saves the scene info, not the resources.
resources like obj cannot be saved locally, they must be saved on the server into your account folder

**Comment by sushmitacse** [comment]
Thanks but when I am trying to create an account of me in the server , its saying problem undefined.. PFA the screenshot of the above mentioned issue.
<img width="1440" alt="screen shot 2017-11-26 at 1 28 30 am" src="https://user-images.githubusercontent.com/17617294/33234251-7b40e176-d249-11e7-95b4-42ecf984325f.png">

**Comment by jagenjo** [comment]
you havent installed litefileserver correctly.

follow the guide of the web, it seems you havent create the user for the DB.

**Comment by sushmitacse** [comment]
Am using MAC OSX. when I am doing "sudo chown -R :www-data * " inside the src folder of litefilesystem.js its giving me a warning "chown: www-data: illegal group name" as a result of which my install.php is giving me a warning. And am not able to login to server.

**Comment by sushmitacse** [comment]
<img width="1440" alt="screen shot 2017-11-27 at 4 21 58 pm" src="https://user-images.githubusercontent.com/17617294/33263612-7e597948-d390-11e7-9e8f-d0d83464002d.png">
even after logging in to the server, after saving a scene with .obj files and mesh rendering with .jpg files and while loading the scene its giving an error saying "error loading scene:0"
<img width="1440" alt="screen shot 2017-11-27 at 4 30 18 pm" src="https://user-images.githubusercontent.com/17617294/33263596-6dd8ff44-d390-11e7-83f0-917c9ed845ee.png">

**Comment by sushmitacse** [comment]
how to resolve this ?

**Comment by jagenjo** [comment]
which HTTP server do you use?

**Comment by sushmitacse** [comment]
I am using XAMPP cross-platform web-server which has apache http web server

**Comment by jagenjo** [comment]
which operative system?

**Comment by sushmitacse** [comment]
Mac osx

**Comment by sushmitacse** [comment]
even tried on windows its giving the same error

**Comment by sushmitacse** [comment]
did you figure out the issue ?

**Comment by jagenjo** [comment]
send me an email to javi.agenjo@gmail.com so I can help you faster

**Comment by coderofsalvation** [comment]
this issue can be closed, and should be fixed by https://github.com/jagenjo/litefilesystem.js/pull/6 
(litefilesystem probably didn't accept .wbin in the screenshot)

**Comment by jagenjo** [comment]
true, thanks
