### ISSUE TITLE
problem in creating an account

### ISSUE THREAD

**Issue by sushmitacse** [jagenjo/webglstudio.js#32]
Thanks but when I am trying to create an account of me in the server , its saying problem undefined.. PFA the screenshot of the above mentioned issue.
<img width="1440" alt="screen shot 2017-11-26 at 1 28 30 am" src="https://user-images.githubusercontent.com/17617294/33234317-b0da2cc4-d24a-11e7-853d-f9fb78b6a022.png">

**Comment by coderofsalvation** [comment]
I think we can close this issue?

**Comment by jagenjo** [comment]
yes, probably a problematic installation
