### ISSUE TITLE
./editor/fileserver should not be gitignored by default

### ISSUE THREAD

**Issue by Yugloocamai** [jagenjo/webglstudio.js#36]
For obvious reasons.  This should be left up to the end user.  Do not .gitignore files that don't exist in this repository, but could possibly be added at a later point.

**Comment by jagenjo** [comment]
It doesnt exist in this repository but it exist in all the installations of WebGLStudio (it is the recommended folder to install litefileserver).

If I do not add it to the gitignore then when I commit I could commit my whole fileserver system to the repository (several gigabytes). 

So I think is much safer to add it to the gitignore

**Comment by Yugloocamai** [comment]
Why would that whole folder be added when you commit, unless you explicitly added it?  Git doesn't add files to a commit unless you tell it to.

**Comment by jagenjo** [comment]
git add * 

yep, Im lazy as that, but also it could happend. Anyway, that folder should NEVER be in the repository
