### ISSUE TITLE
Proposal: Export to gltf format?

### ISSUE THREAD

**Issue by chrisjallen** [jagenjo/webglstudio.js#37]
Exporting to obj is good, but doesnt include all the great rich features that your application is capable of, embedding shaders, keyframe animations etc. To me this seems quite a big deal breaker from inclusion of other users. At the moment I have my own engine, proposal to adjust the json you export into a common format like gltf, seemingly very similar would allow others not using the LiteScene.js. Such a great tool, youve done incredible work and the best implementation of a 3d editor on web out there, but cant use it given its output.

**Comment by coderofsalvation** [comment]
@chrisjallen thanks for reaching out.

I'm afraid gltf doesn't support lots of features like webglstudio's output (graph networks, scripts).
Maybe you could just write a simple json to gltf converter?
Most development is focused in other areas afaik, so it would be the fastest approach.

**Comment by chrisjallen** [comment]
ah ok thanks, understood, I just might look into that conversion.
