### ISSUE TITLE
Does WebGLStudio support installation on Windows?

### ISSUE THREAD

**Issue by KnightCoder** [jagenjo/webglstudio.js#46]
Does WebGLStudio support installation on Windows? 

I tried installing LiteFileServer but it was failing, since it was calling a POSIX function which isn't supported by Windows. And WebGLStudio is dependent on LiteFileServer. 

Hence, please confirm and help to support this installation.

**Comment by jagenjo** [comment]
I never tryed it on windows so the answer is no. Some LiteFileServer functions probably expect a file system based on linux. That doesnt mean it cannot be ported, probably changing a couple of lines would be enough, just search for the errors and check if there is a version for windows of the same functions, in php that should be easy.
