### ISSUE TITLE
How to set collision boxes?

### ISSUE THREAD

**Issue by TheRealDigitalMaster** [jagenjo/webglstudio.js#59]
I am making a game engine with webglstudio.js, and there is so many options that I can't find some of the features. Is there a way to set a collision box with the camera? So far in my game test the camera can go through the entity and the walls.
![image](https://user-images.githubusercontent.com/112659665/208465017-c61cc303-6516-4197-84f7-0df7aba7843e.png)
![image](https://user-images.githubusercontent.com/112659665/208465030-54e29bfd-dba9-4217-b4d6-28116183cf28.png)
![image](https://user-images.githubusercontent.com/112659665/208465044-d953cd51-902e-4e72-9ea2-ed481529cffa.png)

**Comment by jagenjo** [comment]
There is no collisions in Webglstudio, sorry. It was never meant to do games.
I will recommend you to check playcanvas.com, thats way better.

Cheers

**Comment by TheRealDigitalMaster** [comment]
Ok thanks :D
